import { relations, sql } from "drizzle-orm";
import {
  boolean,
  check,
  index,
  integer,
  pgTable,
  text,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

import {
  auditColumns,
  bps,
  invoiceStatusEnum,
  money,
  paymentMethodEnum,
  primaryId,
  ts,
} from "./_shared.js";
import { customers } from "./crm.js";
import { repairOrders } from "./operations.js";
import { locations, organizations, users } from "./tenancy.js";

export const invoices = pgTable(
  "invoices",
  {
    id: primaryId(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    locationId: uuid("location_id").references(() => locations.id, {
      onDelete: "set null",
    }),

    invoiceNumber: integer("invoice_number").notNull(),

    /** At most one invoice per repair order, enforced by the unique index. */
    repairOrderId: uuid("repair_order_id").references(() => repairOrders.id, {
      onDelete: "restrict",
    }),
    customerId: uuid("customer_id")
      .notNull()
      .references(() => customers.id, { onDelete: "restrict" }),

    status: invoiceStatusEnum("status").notNull().default("draft"),

    // --- Money -------------------------------------------------------------
    laborSubtotalCents: money("labor_subtotal_cents").notNull().default(0),
    partsSubtotalCents: money("parts_subtotal_cents").notNull().default(0),
    feesSubtotalCents: money("fees_subtotal_cents").notNull().default(0),
    discountCents: money("discount_cents").notNull().default(0),
    taxRateBps: bps("tax_rate_bps").notNull().default(0),
    taxCents: money("tax_cents").notNull().default(0),
    totalCents: money("total_cents").notNull().default(0),

    /** Maintained alongside every payment insert, inside the transaction. */
    amountPaidCents: money("amount_paid_cents").notNull().default(0),

    /**
     * Generated by Postgres so the balance can never disagree with the two
     * columns it derives from, no matter which code path wrote them.
     */
    balanceCents: money("balance_cents").generatedAlwaysAs(
      sql`total_cents - amount_paid_cents`,
    ),

    issuedAt: ts("issued_at"),
    dueAt: ts("due_at"),
    sentAt: ts("sent_at"),
    paidAt: ts("paid_at"),

    voidedAt: ts("voided_at"),
    voidedByUserId: uuid("voided_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    voidReason: text("void_reason"),

    notes: text("notes"),

    /** SHA-256 of the public payment-link token; the token itself is not stored. */
    publicTokenHash: text("public_token_hash"),
    publicTokenExpiresAt: ts("public_token_expires_at"),

    remindersEnabled: boolean("reminders_enabled").notNull().default(true),
    reminderCount: integer("reminder_count").notNull().default(0),
    lastReminderAt: ts("last_reminder_at"),

    ...auditColumns(),
  },
  (table) => [
    uniqueIndex("invoices_org_number_key").on(table.orgId, table.invoiceNumber),
    uniqueIndex("invoices_repair_order_key").on(table.repairOrderId),
    index("invoices_org_status_idx").on(table.orgId, table.status),
    index("invoices_customer_idx").on(table.customerId),
    index("invoices_org_location_idx").on(table.orgId, table.locationId),
    index("invoices_due_idx")
      .on(table.orgId, table.dueAt)
      .where(sql`status in ('sent', 'partial')`),
    check("invoices_amount_paid_range", sql`amount_paid_cents >= 0`),
    check("invoices_no_overpayment", sql`amount_paid_cents <= total_cents`),
  ],
);

export const invoicePayments = pgTable(
  "invoice_payments",
  {
    id: primaryId(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    invoiceId: uuid("invoice_id")
      .notNull()
      .references(() => invoices.id, { onDelete: "cascade" }),

    method: paymentMethodEnum("method").notNull(),
    amountCents: money("amount_cents").notNull(),
    reference: text("reference"),
    paidAt: ts("paid_at")
      .notNull()
      .default(sql`now()`),

    recordedByUserId: uuid("recorded_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),

    /**
     * Stripe delivers webhooks at least once. The unique index makes a replay a
     * no-op instead of a duplicate payment.
     */
    stripePaymentIntentId: text("stripe_payment_intent_id"),
    stripeCheckoutSessionId: text("stripe_checkout_session_id"),

    /** Set when a payment is reversed rather than deleted. */
    reversedAt: ts("reversed_at"),
    reversalOfPaymentId: uuid("reversal_of_payment_id"),

    ...auditColumns(),
  },
  (table) => [
    index("invoice_payments_invoice_idx").on(table.invoiceId, table.paidAt),
    index("invoice_payments_org_idx").on(table.orgId, table.paidAt),
    uniqueIndex("invoice_payments_stripe_intent_key").on(
      table.stripePaymentIntentId,
    ),
    uniqueIndex("invoice_payments_stripe_session_key").on(
      table.stripeCheckoutSessionId,
    ),
    check("invoice_payments_amount_nonzero", sql`amount_cents <> 0`),
  ],
);

export const invoicesRelations = relations(invoices, ({ one, many }) => ({
  org: one(organizations, {
    fields: [invoices.orgId],
    references: [organizations.id],
  }),
  repairOrder: one(repairOrders, {
    fields: [invoices.repairOrderId],
    references: [repairOrders.id],
  }),
  customer: one(customers, {
    fields: [invoices.customerId],
    references: [customers.id],
  }),
  payments: many(invoicePayments),
}));

export const invoicePaymentsRelations = relations(
  invoicePayments,
  ({ one }) => ({
    invoice: one(invoices, {
      fields: [invoicePayments.invoiceId],
      references: [invoices.id],
    }),
  }),
);
