packages:
  - packages/*
  - apps/*
  - infra

allowBuilds:
  esbuild: true
  "@swc/core": true
  "@tailwindcss/oxide": true

onlyBuiltDependencies:
  - esbuild
  - "@swc/core"
  - "@tailwindcss/oxide"
