/**
 * Bundles the existing convex/ modules against the AWS runtime, plus the
 * Lambda entrypoints (HTTP API + scheduled-job drainer).
 *
 * The whole migration strategy rests on the ported functions being unmodified,
 * so nothing here rewrites their source. Instead the two Convex-generated
 * imports every module uses are aliased to the runtime:
 *
 *   ./_generated/server -> aws/runtime/functions.ts   (query, mutation, ...)
 *   ./_generated/api    -> aws/runtime/api.ts         (api, internal proxies)
 *
 * `convex/values` is deliberately left alone: v and ConvexError are pure
 * validator/error helpers with no server dependency, so the real package is
 * used as-is.
 *
 * Usage:
 *   node build.mjs            bundle registry + Lambda handlers
 *   node build.mjs --list     print the modules that would be bundled
 *   node build.mjs --registry-only
 */
import { build } from "esbuild";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const convexDir = join(repoRoot, "convex");
const outDir = join(here, "dist");

/** Convex modules to bundle: every .ts file except tests and generated code. */
export function convexModules() {
  return readdirSync(convexDir)
    .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && !f.endsWith(".d.ts"))
    .map((f) => f.replace(/\.ts$/, ""))
    .sort();
}

/**
 * Generates the entry point: imports every module and registers it under its
 * module name, which is what turns `internal.email.sendInvoiceEmail` into a
 * resolvable path at runtime.
 */
function generateRegistry(modules) {
  const imports = modules
    .map((m, i) => `import * as m${i} from "../../convex/${m}.ts";`)
    .join("\n");
  const registrations = modules
    .map((m, i) => `registerModule(${JSON.stringify(m)}, m${i});`)
    .join("\n");

  // The bundle inlines the runtime, so it owns the single function registry.
  // Anything that needs to call a registered function -- the Lambda handlers,
  // the scheduled-job drainer, the tests -- must therefore take api/internal
  // and Runtime from here rather than importing runtime/ separately, or it
  // would get a second, empty registry.
  return `// Generated by aws/build.mjs -- do not edit.
import { registerModule } from "../runtime/functions.ts";
${imports}

${registrations}

export { api, internal, lookup, lookupPublic, registeredPaths } from "../runtime/functions.ts";
export { Runtime } from "../runtime/context.ts";
export { generateId } from "../runtime/db.ts";
export { claimDueJobs, markJobFailed, markJobSucceeded } from "../runtime/scheduler.ts";
export { bearerToken, identityFromClaims } from "../runtime/auth.ts";
`;
}

const aliasPlugin = {
  name: "convex-generated-alias",
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /_generated\/(server|api)(\.js)?$/ }, (args) => {
      const which = args.path.includes("/api") ? "api" : "functions";
      return { path: join(here, "runtime", `${which}.ts`) };
    });
    // Type-only imports of dataModel are erased, but esbuild still resolves the
    // specifier; point it at a stub so the bundle does not need Convex codegen.
    pluginBuild.onResolve({ filter: /_generated\/dataModel(\.d\.ts|\.js)?$/ }, () => ({
      path: join(here, "runtime", "dataModel.ts"),
    }));
  },
};

const external = [
  "pg",
  "pg-native",
  "@aws-sdk/*",
  "stripe",
  "openai",
  "jspdf",
  "jspdf-autotable",
  "aws-jwt-verify",
  "aws-jwt-verify/*",
  "web-push",
];

const modules = convexModules();

if (process.argv.includes("--list")) {
  console.log(`${modules.length} modules:`);
  for (const m of modules) console.log(`  ${m}`);
  process.exit(0);
}

mkdirSync(join(here, "generated"), { recursive: true });
mkdirSync(outDir, { recursive: true });
const registryPath = join(here, "generated", "registry.ts");
writeFileSync(registryPath, generateRegistry(modules));

await build({
  entryPoints: [registryPath],
  outfile: join(outDir, "registry.js"),
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  sourcemap: true,
  external,
  plugins: [aliasPlugin],
  logLevel: "info",
});

console.log(`Bundled ${modules.length} convex modules -> ${outDir}/registry.js`);

if (process.argv.includes("--registry-only")) process.exit(0);

// Handlers import ../generated/registry.ts so they share one registry instance
// per bundle. Each Lambda gets its own copy of the registry + handler code.
await build({
  entryPoints: {
    http: join(here, "handlers", "http.ts"),
    drainer: join(here, "handlers", "drainer.ts"),
  },
  outdir: outDir,
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  sourcemap: true,
  external,
  plugins: [aliasPlugin],
  logLevel: "info",
  banner: {
    // AWS Lambda ESM: ensure __dirname-style paths work if a dep needs them.
    js: "import { createRequire } from 'module'; const require = createRequire(import.meta.url);",
  },
});

writeFileSync(
  join(outDir, "package.json"),
  JSON.stringify(
    {
      name: "mechpro-lambda",
      private: true,
      type: "module",
      dependencies: {
        pg: readDepVersion("pg"),
        stripe: readDepVersion("stripe") ?? readRootDepVersion("stripe"),
        openai: readDepVersion("openai") ?? readRootDepVersion("openai"),
        "aws-jwt-verify": readDepVersion("aws-jwt-verify"),
        "jspdf": readDepVersion("jspdf") ?? readRootDepVersion("jspdf") ?? "4.2.1",
        "jspdf-autotable":
          readDepVersion("jspdf-autotable") ?? readRootDepVersion("jspdf-autotable") ?? "5.0.8",
        convex: readRootDepVersion("convex"),
        "@usehercules/sdk": readRootDepVersion("@usehercules/sdk"),
        "escape-html": readRootDepVersion("escape-html"),
        "web-push": readRootDepVersion("web-push"),
      },
    },
    null,
    2,
  ),
);

// @aws-sdk/* stays external: Node.js 22 Lambda runtimes ship SDK v3.

console.log("Installing Lambda production node_modules into dist/ …");
execSync("npm install --omit=dev --no-package-lock", { cwd: outDir, stdio: "inherit" });

// Lambda looks up handler "http.handler" → http.js export handler
console.log(`Lambda artifacts ready in ${outDir}`);

function readDepVersion(name) {
  try {
    const pkg = JSON.parse(readFileSync(join(here, "package.json"), "utf8"));
    return pkg.dependencies?.[name] ?? pkg.devDependencies?.[name];
  } catch {
    return undefined;
  }
}

function readRootDepVersion(name) {
  try {
    const pkg = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8"));
    return pkg.dependencies?.[name] ?? pkg.devDependencies?.[name];
  } catch {
    return undefined;
  }
}
