/**
 * Bundles the existing convex/ modules against the AWS runtime.
 *
 * The whole migration strategy rests on the ported functions being unmodified,
 * so nothing here rewrites their source. Instead the two Convex-generated
 * imports every module uses are aliased to the runtime:
 *
 *   ./_generated/server -> aws/runtime/functions.ts   (query, mutation, ...)
 *   ./_generated/api    -> aws/runtime/api.ts         (api, internal proxies)
 *
 * `convex/values` is deliberately left alone: v and ConvexError are pure
 * validator/error helpers with no server dependency, so the real package is
 * used as-is.
 *
 * Usage:
 *   node build.mjs            bundle every convex module for Lambda
 *   node build.mjs --list     print the modules that would be bundled
 */
import { build } from "esbuild";
import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const convexDir = join(repoRoot, "convex");
const outDir = join(here, "dist");

/** Convex modules to bundle: every .ts file except tests and generated code. */
export function convexModules() {
  return readdirSync(convexDir)
    .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && !f.endsWith(".d.ts"))
    .map((f) => f.replace(/\.ts$/, ""))
    .sort();
}

/**
 * Generates the entry point: imports every module and registers it under its
 * module name, which is what turns `internal.email.sendInvoiceEmail` into a
 * resolvable path at runtime.
 */
function generateRegistry(modules) {
  const imports = modules
    .map((m, i) => `import * as m${i} from "../../convex/${m}.ts";`)
    .join("\n");
  const registrations = modules
    .map((m, i) => `registerModule(${JSON.stringify(m)}, m${i});`)
    .join("\n");

  // The bundle inlines the runtime, so it owns the single function registry.
  // Anything that needs to call a registered function -- the Lambda handlers,
  // the scheduled-job drainer, the tests -- must therefore take api/internal
  // and Runtime from here rather than importing runtime/ separately, or it
  // would get a second, empty registry.
  return `// Generated by aws/build.mjs -- do not edit.
import { registerModule } from "../runtime/functions.ts";
${imports}

${registrations}

export { api, internal, lookup, lookupPublic, registeredPaths } from "../runtime/functions.ts";
export { Runtime } from "../runtime/context.ts";
export { generateId } from "../runtime/db.ts";
export { claimDueJobs, markJobFailed, markJobSucceeded } from "../runtime/scheduler.ts";
export {
  claimStorageDeletions,
  drainStorageDeletions,
  executeStorageDeletion,
  markStorageDeletionFailed,
  markStorageDeletionSucceeded,
} from "../runtime/storageDeletions.ts";
export { bearerToken, identityFromClaims } from "../runtime/auth.ts";
`;
}

const aliasPlugin = {
  name: "convex-generated-alias",
  setup(pluginBuild) {
    pluginBuild.onResolve({ filter: /_generated\/(server|api)(\.js)?$/ }, (args) => {
      const which = args.path.includes("/api") ? "api" : "functions";
      return { path: join(here, "runtime", `${which}.ts`) };
    });
    // Type-only imports of dataModel are erased, but esbuild still resolves the
    // specifier; point it at a stub so the bundle does not need Convex codegen.
    pluginBuild.onResolve({ filter: /_generated\/dataModel(\.d\.ts|\.js)?$/ }, () => ({
      path: join(here, "runtime", "dataModel.ts"),
    }));
  },
};

const modules = convexModules();

if (process.argv.includes("--list")) {
  console.log(`${modules.length} modules:`);
  for (const m of modules) console.log(`  ${m}`);
  process.exit(0);
}

mkdirSync(join(here, "generated"), { recursive: true });
const registryPath = join(here, "generated", "registry.ts");
writeFileSync(registryPath, generateRegistry(modules));

await build({
  entryPoints: [registryPath],
  outfile: join(outDir, "registry.js"),
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  sourcemap: true,
  // Provided by the Lambda layer / node_modules rather than inlined.
  external: [
    "pg",
    "pg-native",
    "@aws-sdk/*",
    "stripe",
    "openai",
    "jspdf",
    "jspdf-autotable",
  ],
  plugins: [aliasPlugin],
  logLevel: "info",
});

await build({
  entryPoints: [join(here, "handlers", "http.ts")],
  outfile: join(outDir, "http.js"),
  bundle: true,
  platform: "node",
  target: "node22",
  format: "esm",
  sourcemap: true,
  external: [
    "pg",
    "pg-native",
    "aws-jwt-verify",
    "@aws-sdk/*",
    "stripe",
    "openai",
    "jspdf",
    "jspdf-autotable",
  ],
  plugins: [aliasPlugin],
  logLevel: "info",
});

await build({
  entryPoints: [join(here, "functions", "storageDeletionWorker.ts")],
  outfile: join(outDir, "storageDeletionWorker.js"),
  bundle: true,
  platform: "node",
  target: "node22",
  format: "cjs",
  sourcemap: true,
  external: ["pg-native", "@aws-sdk/*"],
  logLevel: "info",
});

console.log(`Bundled ${modules.length} convex modules -> ${outDir}/registry.js`);
console.log(`Bundled HTTP handler -> ${outDir}/http.js`);
console.log(`Bundled storage deletion worker -> ${outDir}/storageDeletionWorker.js`);
