/**
 * Multi-tenant Inspections Handler
 * Stores vehicle inspection records in Aurora PostgreSQL for the current shop.
 */
import { createInspection, listInspections } from './db';

const getShopId = (event: any): string | undefined => {
  const claims = event?.requestContext?.authorizer?.claims ?? {};
  return claims['custom:shop_id'] ?? claims.shop_id ?? claims['custom:shopId'] ?? claims.shopId;
};

const parseBody = (event: any): Record<string, any> | null => {
  if (!event?.body) {
    return null;
  }

  try {
    return typeof event.body === 'string' ? JSON.parse(event.body) : event.body;
  } catch (error) {
    throw new Error('Invalid JSON body');
  }
};

export const handler = async (event: any): Promise<any> => {
  try {
    const shopId = getShopId(event);
    if (!shopId) {
      return { statusCode: 403, body: JSON.stringify({ error: 'Shop ID not found' }) };
    }

    const method = event.httpMethod;

    if (method === 'GET') {
      const inspections = await listInspections(shopId);
      return {
        statusCode: 200,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(inspections),
      };
    }

    if (method === 'POST') {
      const body = parseBody(event) ?? {};
      const { customer_id, vehicle_vin, findings } = body;

      if (!customer_id || !vehicle_vin) {
        return {
          statusCode: 400,
          body: JSON.stringify({ error: 'Missing required inspection fields' }),
        };
      }

      const inspection = await createInspection(shopId, { customer_id, vehicle_vin, findings, ai_analysis: 'AI analysis generated by OpenAI' });
      return {
        statusCode: 201,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(inspection),
      };
    }

    return { statusCode: 405, body: JSON.stringify({ error: 'Method not allowed' }) };
  } catch (error) {
    console.error('Error:', error);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: 'Internal server error', message: String(error) }),
    };
  }
};
